# -*- coding: utf-8 -*-
"""Proje ödevi...19*******.ipynb adlı not defterinin kopyası

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vCrn-nz3JemrpmITwSnsih6apDzSTE0u
"""

print("Hoşgeldiniz. Deşarj yapıp yapamayacağnızı öğrenmek için lütfen aşağıda ki soruları doğru bir şekilde cevaplayınız.")
print("1- Metal Sanayi\n2- Cam Sanayi\n3- Ağaç Mamulleri Ve Mobilya Sanayi\n4- Petrol Sanayi\n5- Sağlık Kuruluşu\n6- Tekstil Sanayi\n7- Taşıt Fabrikaları Ve Tamirhaneleri\n8- Kimya Sanayi\n9- Kömür Hazırlama, İşleme Ve Enerji Üretme Tesisleri\n10- Maden Sanayi\n11- Seri Makine İmalatı, Elektrik Makineleri Ve Teçhizatı, Yedek Parça Sanayi\n12- Karışık Endüstriyel\n13- Selüloz, Kağıt, Karton Ve Benzeri Sanayiler\n14- İçki Sanyi\n15- Gıda Sanayi\n16- Endüstriyel Nitelikli\n17- Deri, Deri Mamulleri Ve Benzeri Sanayiler\n18- Evsel Nitelikli\n19- Atıksuların Atıksu Altyapı Tesisleri")
x=int(input("Yukarıda bulunan işletmelerden size ait olanın sıra numarasını giriniz : "))
if x==1:
    print("Metal Sanayi atıksularının, alıcı ortama deşarj standartlarına uyugunluğuna bakmak için lütfen verilecek olan parametrelere işletmenizin değerlerini net ve doğru bir şekilde giriniz.")
    KOİ=float(input("Kimyasal Oksijen İhtiyacı (KOİ) değerini giriniz="))
    pH=float(input("pH değerini giriniz="))
    renk=float(input("Renk değerini giriniz="))
    yağ=float(input("Yağ ve Gres değerini giriniz="))
    AKM=float(input("Askıda Katı Madde (AKM) değerini giriniz="))
    ZSF=float(input("Balık Biyodeneyi (ZSF) değerini giriniz="))
    ÇKM=float(input("Çökebilir Katı Madde değerini giriniz="))
    aktifklor=float(input("Aktif Klor değerini giriniz="))
    toplamsiyanür=float(input("Toplam Siyanür değerini giriniz="))
    Pb=float(input("Kurşun (Pb) değerini giriniz="))
    sülfür=float(input("Sülfür değerini giriniz="))
    Al=float(input("Alüminyum (Al) değerini giriniz="))
    Zn=float(input("Çinko (Zn) değerini giriniz="))
    toplamkrom=float(input("Toplam Krom değerini giriniz="))
    arsenik=float(input("Arsenik değerini giriniz="))
    florür=float(input("Florür değerini giriniz="))
    Fe=float(input("Demir (Fe) değerini giriniz="))
    Hg=float(input("Cıva (Hg) değerini giriniz="))
    Cd=float(input("Kadminyum (Cd) değerini giriniz="))
    Ni=float(input("Nikel (Ni) değerini giriniz="))
    Cu=float(input("Bakır (Cu) değerini giriniz="))
    amonyumazotu=float(input("Amonyum Azotu değerini giriniz="))
    nitritazotu=float(input("Nitrit Azotu değerini giriniz="))
    Ag=float(input("Gümüş (Ag) değerini giriniz="))
    import openpyxl
    from openpyxl import Workbook,load_workbook
    import pandas as pd
    book=load_workbook("metal.xlsx")
    sheet=book.active
    df=pd.read_excel("metal.xlsx")
    print(df)
    print("(Girdiğiniz işletmenin, parametrelerinin en fazla alabileceği değerler yukarıdaki tabloda belirtilmiştir.)")
    if KOİ<=(sheet["B2"].value) and 6<=(pH)<=9 and renk<=(sheet["B4"].value) and yağ<=(sheet["B5"].value) and AKM<=(sheet["B6"].value) and ZSF<=(sheet["B7"].value) and ÇKM<=(sheet["B8"].value) and aktifklor<=(sheet["B9"].value) and toplamsiyanür<=(sheet["B10"].value) and Pb<=(sheet["B11"].value) and sülfür<=(sheet["B12"].value) and Al<=(sheet["B13"].value) and Zn<=(sheet["B14"].value) and toplamkrom<=(sheet["B15"].value) and arsenik<=(sheet["B16"].value) and florür<=(sheet["B17"].value) and Fe<=(sheet["B18"].value) and Hg<=(sheet["B19"].value) and Cd<=(sheet["B20"].value) and Ni<=(sheet["B21"].value) and Cu<=(sheet["B22"].value) and amonyumazotu<=(sheet["B23"].value) and nitritazotu<=(sheet["B24"].value) and Ag<=(sheet["B25"].value):
      print("Girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılabilir:).")
    else:
      print("Malesef girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılamaz.")
if x==2:
    print("Cam Sanayi atıksularının, alıcı ortama deşarj standartlarına uyugunluğuna bakmak için lütfen verilecek olan parametrelere işletmenizin değerlerini net ve doğru bir şekilde giriniz.")
    KOİ=float(input("KOİ değerini giriniz="))
    pH=float(input("pH değerini giriniz="))
    Pb=float(input("Kurşun (Pb) değerini giriniz="))
    sülfat=float(input("Sülfat değerini giriniz="))
    florür=float(input("Florür değerini giriniz="))
    Ni=float(input("Nikel (Ni) değerini giriniz="))
    Ag=float(input("Gümüş (Ag) değerini giriniz="))
    import openpyxl
    from openpyxl import Workbook,load_workbook
    import pandas as pd
    book=load_workbook("cam.xlsx")
    sheet=book.active
    df=pd.read_excel("cam.xlsx")
    print(df)
    print("(Girdiğiniz işletmenin, parametrelerinin en fazla alabileceği değerler yukarıdaki tabloda belirtilmiştir.)")
    if KOİ<=(sheet["B2"].value) and 6<=(pH)<=9 and Pb<=(sheet["B4"].value) and sülfat<=(sheet["B5"].value) and florür<=(sheet["B6"].value) and Ni<=(sheet["B7"].value) and Ag<=(sheet["B8"].value):
      print("Girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılabilir:).")
    else:
      print("Malesef girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılamaz.")
if x==3:
    print("Ağaç Mamullaer ve Mobilya Sanayi atıksularının, alıcı ortama deşarj standartlarına uyugunluğuna bakmak için lütfen verilecek olan parametrelere işletmenizin değerlerini net ve doğru bir şekilde giriniz.")
    KOİ=float(input("Kimyasal Oksijen İhtiyacı (KOİ) değerini giriniz="))
    pH=float(input("pH değerini giriniz="))
    ÇKM=float(input("Çökebilir Katı Madde değerini giriniz="))
    import openpyxl
    from openpyxl import Workbook,load_workbook
    import pandas as pd
    book=load_workbook("mobilya.xlsx")
    sheet=book.active
    df=pd.read_excel("mobilya.xlsx")
    print(df)
    print("(Girdiğiniz işletmenin, parametrelerinin en fazla alabileceği değerler yukarıdaki tabloda belirtilmiştir.)")
    if KOİ<=(sheet["B2"].value) and 6<=(pH)<=9 and ÇKM<=(sheet["B4"].value):
      print("Girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılabilir:).")
    else:
      print("Malesef girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılamaz.")
if x==4:
    print("Petrol Sanayi atıksularının, alıcı ortama deşarj standartlarına uyugunluğuna bakmak için lütfen verilecek olan parametrelere işletmenizin değerlerini net ve doğru bir şekilde giriniz.")
    KOİ=float(input("Kimyasal Oksijen İhtiyacın (KOİ) değerini giriniz="))
    pH=float(input("pH değerini giriniz="))
    renk=float(input("Renk değerini giriniz="))
    yağ=float(input("Yağ ve Gres değerini giriniz="))
    AKM=float(input("Askıda Katı Madde (AKM) değerini giriniz="))
    ZSF=float(input("Balık Biyodeneyi (ZSF) değerini giriniz="))
    amonyumazotu=float(input("Amonyum Azotu değerini giriniz="))
    Cl=float(input("Serbest Klor değerini giriniz="))
    toplamsiyanür=float(input("Toplam Siyanür değerini giriniz="))
    sülfat=float(input("Sülfat değerini giriniz="))
    sülfür=float(input("Sülfür değerini giriniz="))
    fenol=float(input("Fenol değerini giriniz="))
    Zn=float(input("Çinko (Zn) değerini giriniz="))
    krom=float(input("Krom değerini giriniz="))
    hidrokarbonlar=float(input("Hidrokarbonlar değerini giriniz="))
    Na=float(input("Sodyum (Na) değerini giriniz="))
    Fe=float(input("Demir (Fe) değerini giriniz="))
    Hg=float(input("Cıva (Hg) değerini giriniz="))
    Cd=float(input("Kadminyum (Cd) değerini giriniz="))
    Pb=float(input("Kurşun (Pb) değerini giriniz="))
    Cu=float(input("Bakır (Cu) değerini giriniz="))
    import openpyxl
    from openpyxl import Workbook,load_workbook
    import pandas as pd
    book=load_workbook("petrol.xlsx")
    sheet=book.active
    df=pd.read_excel("petrol.xlsx")
    print(df)
    print("(Girdiğiniz işletmenin, parametrelerinin en fazla alabileceği değerler yukarıdaki tabloda belirtilmiştir.)")
    if KOİ<=(sheet["B2"].value) and 6<=(pH)<=9 and renk<=(sheet["B4"].value) and yağ<=(sheet["B5"].value) and AKM<=(sheet["B6"].value) and ZSF<=(sheet["B7"].value) and amonyumazotu<=(sheet["B8"].value) and Cl<=(sheet["B9"].value) and toplamsiyanür<=(sheet["B10"].value) and sülfat<=(sheet["B11"].value) and sülfür<=(sheet["B12"].value) and fenol<=(sheet["B13"].value) and Zn<=(sheet["B14"].value) and krom<=(sheet["B15"].value) and hidrokarbonlar<=(sheet["B16"].value) and Na<=(sheet["B17"].value) and Fe<=(sheet["B18"].value) and Hg<=(sheet["B19"].value) and Cd<=(sheet["B20"].value) and Pb<=(sheet["B21"].value) and Cu<=(sheet["B22"].value):
      print("Girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılabilir:).")
    else:
      print("Malesef girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılamaz.")
if x==5:
    print("Sağlık Kuruluşlarından Kaynaklanan atıksuların, alıcı ortama deşarj standartları uyugunluğuna bakmak için lütfen verilecek olan parametrelere işletmenizin değerlerini net ve doğru bir şekilde giriniz.")
    KOİ=float(input("Kimyasal Oksijen İhtiyacı (KOİ) değerini giriniz="))
    pH=float(input("pH değerini giriniz="))
    AKM=float(input("Askıda Katı Madde (AKM) değerini giriniz="))
    ZSF=float(input("Balık Biyodeneyi (ZSF) değerini giriniz="))
    BOİ=float(input("Biyokimyasal Oksijen İhtiyacı (BOİ) değerini giriniz="))
    import openpyxl
    from openpyxl import Workbook,load_workbook
    import pandas as pd
    book=load_workbook("sağlık.xlsx")
    sheet=book.active
    df=pd.read_excel("sağlık.xlsx")
    print(df)
    print("(Girdiğiniz işletmenin, parametrelerinin en fazla alabileceği değerler yukarıdaki tabloda belirtilmiştir.)")
    if KOİ<=(sheet["B2"].value) and 6<=(pH)<=9 and AKM<=(sheet["B4"].value) and ZSF<=(sheet["B5"].value) and BOİ<=(sheet["B6"].value):
      print("Girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılabilir:).")
    else:
      print("Malesef girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılamaz.")
if x==6:
    print("Tekstil Sanayi atıksularının, alıcı ortama deşarj standartlarına uyugunluğuna bakmak için lütfen verilecek olan parametrelere işletmenizin değerlerini net ve doğru bir şekilde giriniz.")
    KOİ=float(input("Kimyasal Ojsijen İhtiyacı (KOİ) değerini giriniz="))
    pH=float(input("pH değerini giriniz="))
    renk=float(input("Renk değerini giriniz="))
    yağ=float(input("Yağ ve Gres değerini giriniz="))
    AKM=float(input("Askıda Katı Madde (AKM) değerini giriniz="))
    ZSF=float(input("Balık Biyodeneyi (ZSF) değerini giriniz="))
    amonyumazotu=float(input("Amonyum Azotu değerini giriniz="))
    serbestklor=float(input("Serbest Klor değerini giriniz="))
    toplamkrom=float(input("Toplam Krom değerini giriniz="))
    sülfür=float(input("Sülfür değerini giriniz="))
    sülfit=float(input("Sülfit değerini giriniz="))
    fenol=float(input("Fenol değerini giriniz="))
    Zn=float(input("Çinko (Zn) değerini giriniz="))
    import openpyxl
    from openpyxl import Workbook,load_workbook
    import pandas as pd
    book=load_workbook("tekstil.xlsx")
    sheet=book.active
    df=pd.read_excel("tekstil.xlsx")
    print(df)
    print("(Girdiğiniz işletmenin, parametrelerinin en fazla alabileceği değerler yukarıdaki tabloda belirtilmiştir.)")
    if KOİ<=(sheet["B2"].value) and 6<=(pH)<=9 and renk<=(sheet["B4"].value) and yağ<=(sheet["B5"].value) and AKM<=(sheet["B6"].value) and ZSF<=(sheet["B7"].value) and amonyumazotu<=(sheet["B8"].value) and serbestklor<=(sheet["B9"].value) and toplamkrom<=(sheet["B10"].value) and sülfür<=(sheet["B11"].value) and sülfit<=(sheet["B12"].value) and fenol<=(sheet["B13"].value) and Zn<=(sheet["B14"].value):
      print("Girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılabilir:).")
    else:
      print("Malesef girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılamaz.")
if x==7:
    print("Taşıt Fabrikaları ve Tamirhaneleri atıksularının, alıcı ortama deşarj standartlarına uyugunluğuna bakmak için lütfen verilecek olan parametrelere işletmenizin değerlerini net ve doğru bir şekilde giriniz.")
    KOİ=float(input("Kimyasal Oksijen İhtiyacı (KOİ) değerini giriniz="))
    pH=float(input("pH değerini giriniz="))
    renk=float(input("Renk değerini giriniz="))
    yağ=float(input("Yağ ve Gres değerini giriniz="))
    AKM=float(input("Askıda Katı Madde (AKM) değerini giriniz="))
    ZSF=float(input("Balık Biyodeneyi (ZSF) değerini giriniz="))
    amonyumazotu=float(input("Amonyum Azotu değerini giriniz="))
    toplamsiyanür=float(input("Toplam Siyanür değerini giriniz="))
    nitritazotu=float(input("Nitrit Azotu değerini giriniz="))
    toplamkrom=float(input("Toplam Krom değerini giriniz="))
    Ni=float(input("Nikel (Ni) değerini giriniz="))
    Cd=float(input("Kadminyum (Cd) değerini giriniz="))
    Fe=float(input("Demir (Fe) değerini giriniz="))
    Al=float(input("Alüminyum (Al) değerini giriniz="))
    Pb=float(input("Kurşun (Pb) değerini giriniz="))
    Cu=float(input("Bakır (Cu) değerini giriniz="))
    Zn=float(input("Çinko (Zn) değerini giriniz="))
    Hg=float(input("Cıva (Hg) değerini giriniz="))
    florür=float(input("Florür değerini giriniz="))
    import openpyxl
    from openpyxl import Workbook,load_workbook
    import pandas as pd
    book=load_workbook("tamirhane.xlsx")
    sheet=book.active
    df=pd.read_excel("tamirhane.xlsx")
    print(df)
    print("(Girdiğiniz işletmenin, parametrelerinin en fazla alabileceği değerler yukarıdaki tabloda belirtilmiştir.)")
    if KOİ<=(sheet["B2"].value) and 6<=(pH)<=9 and renk<=(sheet["B4"].value) and yağ<=(sheet["B5"].value) and AKM<=(sheet["B6"].value) and ZSF<=(sheet["B7"].value) and amonyumazotu<=(sheet["B8"].value) and toplamsiyanür<=(sheet["B9"].value) and nitritazotu<=(sheet["B10"].value) and toplamkrom<=(sheet["B11"].value) and Ni<=(sheet["B12"].value) and Cd<=(sheet["B13"].value) and Fe<=(sheet["B14"].value) and Al<=(sheet["B15"].value) and Pb<=(sheet["B16"].value) and Cu<=(sheet["B17"].value) and Zn<=(sheet["B18"].value) and Hg<=(sheet["B19"].value) and florür<=(sheet["B20"].value):
      print("Girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılabilir:).")
    else:
      print("Malesef girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılamaz.")
if x==8:
    print("Kimya Sanayi atıksularının, alıcı ortama deşarj standartlarına uyugunluğuna bakmak için lütfen verilecek olan parametrelere işletmenizin değerlerini net ve doğru bir şekilde giriniz.")
    KOİ=float(input("Kimyasal Oksijen İhtiyacı (KOİ) değerini giriniz="))
    pH=float(input("pH değerini giriniz="))
    renk=float(input("Renk değerini giriniz="))
    yağ=float(input("Yağ ve Gres değerini giriniz="))
    AKM=float(input("Askıda Katı Madde (AKM) değerini giriniz="))
    ZSF=float(input("Balık Biyodeneyi (ZSF) değerini giriniz="))
    ÇKM=float(input("Çökebilir Katı Madde değerini giriniz="))
    serbestklor=float(input("Serbest Klor (Cl) değerini giriniz="))
    toplamsiyanür=float(input("Toplam Siyanür değerini giriniz="))
    Ba=float(input("Baryum (Ba) değerini giriniz="))
    sülfür=float(input("Sülfür değerini giriniz="))
    fenol=float(input("Fenol değerini giriniz="))
    Zn=float(input("Çinko (Zn) değerini giriniz="))
    toplamkrom=float(input("Toplam Krom değerini giriniz="))
    hidrokarbonlar=float(input("Hidrokarbonlar değerini giriniz="))
    aktifklor=float(input("Aktif Klor değerini giriniz="))
    Fe=float(input("Demir (Fe) değerini giriniz="))
    Hg=float(input("Cıva (Hg) değerini giriniz="))
    Cd=float(input("Toplam Kadminyum değerini giriniz="))
    Pb=float(input("Kurşun (Pb) değerini giriniz="))
    Cu=float(input("Bakır (Cu) değerini giriniz="))
    bor=float(input("Bor değerini giriniz="))
    florür=float(input("Florür değerini giriniz="))
    toplamfosfor=float(input("Toplam Fosfor değerini giriniz="))
    nitratazotu=float(input("Nitrat Azotu değerini giriniz="))
    amonyumazotu=float(input("Amonyum Azotu değerini giriniz="))
    import openpyxl
    from openpyxl import Workbook,load_workbook
    import pandas as pd
    book=load_workbook("kimya.xlsx")
    sheet=book.active
    df=pd.read_excel("kimya.xlsx")
    print(df)
    print("(Girdiğiniz işletmenin, parametrelerinin en fazla alabileceği değerler yukarıdaki tabloda belirtilmiştir.)")
    if KOİ<=(sheet["B2"].value) and 6<=(pH)<=9 and renk<=(sheet["B4"].value) and yağ<=(sheet["B5"].value) and AKM<=(sheet["B6"].value) and ZSF<=(sheet["B7"].value) and ÇKM<=(sheet["B8"].value) and serbestklor<=(sheet["B9"].value) and toplamsiyanür<=(sheet["B10"].value) and Ba<=(sheet["B11"].value) and sülfür<=(sheet["B12"].value) and fenol<=(sheet["B13"].value) and Zn<=(sheet["B14"].value) and toplamkrom<=(sheet["B15"].value) and hidrokarbonlar<=(sheet["B16"].value) and aktifklor<=(sheet["B17"].value) and Fe<=(sheet["B18"].value) and Hg<=(sheet["B19"].value) and Cd<=(sheet["B20"].value) and Pb<=(sheet["B21"].value) and Cu<=(sheet["B22"].value) and bor<=(sheet["B23"].value) and florür<=(sheet["B24"].value) and toplamfosfor<=(sheet["B25"].value) and nitratazotu<=(sheet["B26"].value) and amonyumazotu<=(sheet["B27"].value):
      print("Girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılabilir:).")
    else:
      print("Malesef girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılamaz.")
if x==9:
    print("Kömür Hazırlama, İşleme ve Enerji Üretme Tesisleri atıksularının, alıcı ortama deşarj standartlarına uyugunluğuna bakmak için lütfen verilecek olan parametrelere işletmenizin değerlerini net ve doğru bir şekilde giriniz.")
    KOİ=float(input("Kimyasal Oksijen İhtiyacı (KOİ) değerini giriniz="))
    pH=float(input("pH değerini giriniz="))
    yağ=float(input("Yağ ve Gres değerini giriniz="))
    AKM=float(input("Askıda Katı Madde (AKM) değerini giriniz="))
    ÇKM=float(input("Çökebilir Katı Madde değerini giriniz="))
    sıcaklık=float(input("Sıcaklık değerini giriniz="))
    toplamsiyanür=float(input("Toplam Siyanür değerini giriniz="))
    fenol=float(input("Fenol değerini giriniz="))
    toplamfosfor=float(input("Toplam Fosfor değerini giriniz="))
    serbestklor=float(input("Serbest Klor değerini giriniz="))
    Zn=float(input("Çinko (Zn) değerini giriniz="))
    V=float(input("Vanadyum (V) değerini giriniz="))
    Fe=float(input("Demir (Fe) değerini giriniz="))
    import openpyxl
    from openpyxl import Workbook,load_workbook
    import pandas as pd
    book=load_workbook("kömür.xlsx")
    sheet=book.active
    df=pd.read_excel("kömür.xlsx")
    print(df)
    print("(Girdiğiniz işletmenin, parametrelerinin en fazla alabileceği değerler yukarıdaki tabloda belirtilmiştir.)")
    if KOİ<=(sheet["B2"].value) and 6<=(pH)<=9 and yağ<=(sheet["B4"].value) and AKM<=(sheet["B5"].value) and ÇKM<=(sheet["B6"].value) and sıcaklık<=(sheet["B7"].value) and toplamsiyanür<=(sheet["B8"].value) and fenol<=(sheet["B9"].value) and toplamfosfor<=(sheet["B10"].value) and serbestklor<=(sheet["B11"].value) and Zn<=(sheet["B12"].value) and V<=(sheet["B13"].value) and Fe<=(sheet["B14"].value):
      print("Girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılabilir:).")
    else:
      print("Malesef girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılamaz.")
if x==10:
    print("Maden Sanayi atıksularının, alıcı ortama deşarj standartlarına uyugunluğuna bakmak için lütfen verilecek olan parametrelere işletmenizin değerlerini net ve doğru bir şekilde giriniz.")
    KOİ=float(input("Kimyasal Oksijen İhtiyacı (KOİ) değerini giriniz="))
    pH=float(input("pH değerini giriniz="))
    renk=float(input("Renk değerini giriniz="))
    yağ=float(input("Yağ ve Gres değerini giriniz="))
    AKM=float(input("Askıda Katı Madde (AKM) değerini giriniz="))
    ZSF=float(input("Balık Biyodeneyi (ZSF) değerini giriniz="))
    Pb=float(input("Kurşun (Pb) değerini giriniz="))
    toplamsiyanür=float(input("Toplam Siyanür değerini giriniz="))
    Fe=float(input("Demir (Fe) değerini giriniz="))
    Zn=float(input("Çinko (Zn) değerini giriniz="))
    sülfat=float(input("Sülfat değerini giriniz="))
    Hg=float(input("Cıva (Hg) değerini giriniz="))
    Cu=float(input("Bakır (Cu) değerini giriniz="))
    toplamkrom=float(input("Toplam Krom değerini giriniz="))
    Cd=float(input("Kadminyum (Cd) değerini giriniz="))
    import openpyxl
    from openpyxl import Workbook,load_workbook
    import pandas as pd
    book=load_workbook("maden.xlsx")
    sheet=book.active
    df=pd.read_excel("maden.xlsx")
    print(df)
    print("(Girdiğiniz işletmenin, parametrelerinin en fazla alabileceği değerler yukarıdaki tabloda belirtilmiştir.)")
    if KOİ<=(sheet["B2"].value) and 6<=(pH)<=9 and renk<=(sheet["B4"].value) and yağ<=(sheet["B5"].value) and AKM<=(sheet["B6"].value) and ZSF<=(sheet["B7"].value) and Pb<=(sheet["B8"].value) and toplamsiyanür<=(sheet["B9"].value) and Fe<=(sheet["B10"].value) and Zn<=(sheet["B11"].value) and sülfat<=(sheet["B12"].value) and Hg<=(sheet["B13"].value) and Cu<=(sheet["B14"].value) and toplamkrom<=(sheet["B15"].value) and Cd<=(sheet["B16"].value):
      print("Girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılabilir:).")
    else:
      print("Malesef girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılamaz.")
if x==11:
    print("Seri Makine İmalatı, Elektrik Makineleri ve Techizatı, Yedek Parça Sanayi atıksularının, alıcı ortama deşarj standartlarına uyugunluğuna bakmak için lütfen verilecek olan parametrelere işletmenizin değerlerini net ve doğru bir şekilde giriniz.")
    KOİ=float(input("Kimyasal Oksijen İhtiyacı (KOİ) değerini giriniz="))
    pH=float(input("pH değerini giriniz="))
    yağ=float(input("Yağ ve Gres değerini giriniz="))
    amonyumazotu=float(input("Amonyum Azotu değerini giriniz="))
    krom=float(input("Krom değerini giriniz="))
    Pb=float(input("Kurşun (Pb) değerini giriniz="))
    toplamsiyanür=float(input("Toplam Siyanür değerini giriniz="))
    import openpyxl
    from openpyxl import Workbook,load_workbook
    import pandas as pd
    book=load_workbook("makine.xlsx")
    sheet=book.active
    df=pd.read_excel("makine.xlsx")
    print(df)
    print("(Girdiğiniz işletmenin, parametrelerinin en fazla alabileceği değerler yukarıdaki tabloda belirtilmiştir.)")
    if KOİ<=(sheet["B2"].value) and 6<=(pH)<=9 and yağ<=(sheet["B4"].value) and amonyumazotu<=(sheet["B5"].value) and krom<=(sheet["B6"].value) and Pb<=(sheet["B7"].value) and toplamsiyanür<=(sheet["B8"].value):
      print("Girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılabilir:).")
    else:
      print("Malesef girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılamaz.")
if x==12:
    print("Karışık Endüstriyel natıksularının, alıcı ortama deşarj standartlarına uyugunluğuna bakmak için lütfen verilecek olan parametrelere işletmenizin değerlerini net ve doğru bir şekilde giriniz.")
    KOİ=float(input("Kimyasal Oksijen İhtiyacı (KOİ) değerini giriniz="))
    pH=float(input("pH değerini giriniz="))
    renk=float(input("Renk değerini giriniz="))
    yağ=float(input("Yağ ve Gres değerini giriniz="))
    AKM=float(input("Askıda Katı Madde (AKM) değerini giriniz="))
    ZSF=float(input("Balık Biyodeneyi (ZSF) değerini giriniz="))
    toplamfosfor=float(input("Toplam Fosfor değerini giriniz="))
    toplamsiyanür=float(input("Toplam Siyanür değerini giriniz="))
    florür=float(input("Florür değerini giriniz="))
    toplamkrom=float(input("Toplam Krom değerini giriniz="))
    sülfat=float(input("Sülfat değerini giriniz="))
    Cd=float(input("Kadminyum (Cd) değerini giriniz="))
    Fe=float(input("Demir (Fe) değerini giriniz="))
    Pb=float(input("Kurşun (Pb) değerini giriniz="))
    Cu=float(input("Bakır (Cu) değerini giriniz="))
    Zn=float(input("Çinko (Zn) değerini giriniz="))
    Hg=float(input("Cıva (Hg) değerini giriniz="))
    import openpyxl
    from openpyxl import Workbook,load_workbook
    import pandas as pd
    book=load_workbook("karışık endüstri.xlsx")
    sheet=book.active
    df=pd.read_excel("karışık endüstri.xlsx")
    print(df)
    print("(Girdiğiniz işletmenin, parametrelerinin en fazla alabileceği değerler yukarıdaki tabloda belirtilmiştir.)")
    if KOİ<=(sheet["B2"].value) and 6<=(pH)<=9 and renk<=(sheet["B4"].value) and yağ<=(sheet["B5"].value) and AKM<=(sheet["B6"].value) and ZSF<=(sheet["B7"].value) and toplamfosfor<=(sheet["B8"].value) and toplamsiyanür<=(sheet["B9"].value) and florür<=(sheet["B10"].value) and toplamkrom<=(sheet["B11"].value) and sülfat<=(sheet["B12"].value) and Cd<=(sheet["B13"].value) and Fe<=(sheet["B14"].value) and Pb<=(sheet["B15"].value) and Cu<=(sheet["B16"].value) and Zn<=(sheet["B17"].value) and Hg<=(sheet["B18"].value):
      print("Girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılabilir:).")
    else:
      print("Malesef girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılamaz.")
if x==13:
    print("Selüloz, kağıt, Karton ve Benzeri Sanayileri atıksularının, alıcı ortama deşarj standartlarına uyugunluğuna bakmak için lütfen verilecek olan parametrelere işletmenizin değerlerini net ve doğru bir şekilde giriniz.")
    KOİ=float(input("Kimyasal Oksijen İhtiyacı (KOİ) değerini giriniz="))
    pH=float(input("pH değerini giriniz="))
    renk=float(input("Renk değerini giriniz="))
    AKM=float(input("Askıda Katı Madde (AKM) değerini giriniz="))
    ZSF=float(input("Balık Biyodeneyi (ZSF) değerini giriniz="))
    import openpyxl
    from openpyxl import Workbook,load_workbook
    import pandas as pd
    book=load_workbook("kağıt.xlsx")
    sheet=book.active
    df=pd.read_excel("kağıt.xlsx")
    print(df)
    print("(Girdiğiniz işletmenin, parametrelerinin en fazla alabileceği değerler yukarıdaki tabloda belirtilmiştir.)")
    if KOİ<=(sheet["B2"].value) and 6<=(pH)<=9 and renk<=(sheet["B4"].value) and AKM<=(sheet["B5"].value) and ZSF<=(sheet["B6"].value):
      print("Girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılabilir:).")
    else:
      print("Malesef girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılamaz.")
if x==14:
    print("İçki Sanayi atıksularının, alıcı ortama deşarj standartlarına uyugunluğuna bakmak için lütfen verilecek olan parametrelere işletmenizin değerlerini net ve doğru bir şekilde giriniz.")
    KOİ=float(input("Kimyasal Oksijen İhtiyacı (KOİ) değerini giriniz="))
    pH=float(input("pH değerini giriniz="))
    renk=float(input("Renk değerini giriniz="))
    ÇKM=float(input("Çökebilir Katı Madde değerini giriniz="))
    import openpyxl
    from openpyxl import Workbook,load_workbook
    import pandas as pd
    book=load_workbook("içki.xlsx")
    sheet=book.active
    df=pd.read_excel("içki.xlsx")
    print(df)
    print("(Girdiğiniz işletmenin, parametrelerinin en fazla alabileceği değerler yukarıdaki tabloda belirtilmiştir.)")
    if KOİ<=(sheet["B2"].value) and 6<=(pH)<=9 and renk<=(sheet["B4"].value) and ÇKM<=(sheet["B5"].value):
      print("Girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılabilir:).")
    else:
      print("Malesef girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılamaz.")
if x==15:
    print("Gıda Sanayi atıksularının, alıcı ortama deşarj standartlarına  uyugunluğuna bakmak için lütfen verilecek olan parametrelere işletmenizin değerlerini net ve doğru bir şekilde giriniz.")
    KOİ=float(input("Kimyasal Oksijen İhtiyacı (KOİ) değerini giriniz="))
    pH=float(input("pH değerini giriniz="))
    renk=float(input("Renk değerini giriniz="))
    yağ=float(input("Yağ ve Gres değerini giriniz="))
    AKM=float(input("Askıda Katı Madde (AKM) değerini giriniz="))
    ZSF=float(input("Balık Biyodeneyi (ZSF) değerini giriniz="))
    ÇKM=float(input("Çökebilir Katı Madde değerini giriniz="))
    amonyumazotu=float(input("Amonyum Azotu değerini giriniz="))
    fosfatfosforu=float(input("Fosfat Fosforu değerini giriniz="))
    iletkenlik=float(input("Elektriksel İletkenlik değerini giriniz="))
    import openpyxl
    from openpyxl import Workbook,load_workbook
    import pandas as pd
    book=load_workbook("gıda.xlsx")
    sheet=book.active
    df=pd.read_excel("gıda.xlsx")
    print(df)
    print("(Girdiğiniz işletmenin, parametrelerinin en fazla alabileceği değerler yukarıdaki tabloda belirtilmiştir.)")
    if KOİ<=(sheet["B2"].value) and 6<=(pH)<=9 and renk<=(sheet["B4"].value) and yağ<=(sheet["B5"].value) and AKM<=(sheet["B6"].value) and ZSF<=(sheet["B7"].value) and ÇKM<=(sheet["B8"].value) and amonyumazotu<=(sheet["B9"].value) and fosfatfosforu<=(sheet["B10"].value) and iletkenlik<=(sheet["B11"].value):
      print("Girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılabilir:).")
    else:
      print("Malesef girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılamaz.")
if x==16:
    print("Endüstriyel Nitelikli atıksularının, alıcı ortama deşarj standartlarına uyugunluğuna bakmak için lütfen verilecek olan parametrelere işletmenizin değerlerini net ve doğru bir şekilde giriniz.")
    KOİ=float(input("Kimyasal Oksijen İhtiyacı (KOİ) değerini giriniz="))
    pH=float(input("pH değerini giriniz="))
    renk=float(input("Renk değerini giriniz="))
    yağ=float(input("Yağ ve Gres değerini giriniz="))
    AKM=float(input("Askıda Katı Madde (AKM) değerini giriniz="))
    ZSF=float(input("Balık Biyodeneyi (ZSF) değerini giriniz="))
    ÇKM=float(input("Çökebilir Katı Madde değerini giriniz="))
    sıcaklık=float(input("Sıcaklık değerini giriniz="))
    toplamfosfor=float(input("Toplam Fosfor değerini giriniz="))
    toplamkrom=float(input("Toplam Krom değerini giriniz="))
    toplamsiyanür=float(input("Toplam Siyanür değerini giriniz="))
    Fe=float(input("Demir (Fe) değerini giriniz="))
    florür=float(input("Florür değerini giriniz="))
    sülfit=float(input("Sülfit değerini giriniz="))
    klorür=float(input("Klorür değerini giriniz="))
    sülfat=float(input("Sülfat değerini giriniz="))
    sülfür=float(input("Sülfür değerini giriniz="))
    Pb=float(input("Kurşun (Pb) değerini giriniz="))
    Cd=float(input("Kadminyum (Cd) değerini giriniz="))
    Cu=float(input("Bakır (Cu) değerini giriniz="))
    Zn=float(input("Çinko (Zn) değerini giriniz="))
    Hg=float(input("Cıva (Hg) değerini giriniz="))
    Ni=float(input("Nikel (Ni) değerini giriniz="))
    import openpyxl
    from openpyxl import Workbook,load_workbook
    import pandas as pd
    book=load_workbook("endüstri nitelikli.xlsx")
    sheet=book.active
    df=pd.read_excel("endüstri nitelikli.xlsx")
    print(df)
    print("(Girdiğiniz işletmenin, parametrelerinin en fazla alabileceği değerler yukarıdaki tabloda belirtilmiştir.)")
    if KOİ<=(sheet["B2"].value) and 7<=(pH)<=8.5 and renk<=(sheet["B4"].value) and yağ<=(sheet["B5"].value) and AKM<=(sheet["B6"].value) and ZSF<=(sheet["B7"].value) and ÇKM<=(sheet["B8"].value) and sıcaklık<=(sheet["B9"].value) and toplamfosfor<=(sheet["B10"].value) and toplamkrom<=(sheet["B11"].value) and toplamsiyanür<=(sheet["B12"].value) and Fe<=(sheet["B13"].value) and florür<=(sheet["B14"].value) and sülfit<=(sheet["B15"].value) and klorür<=(sheet["B16"].value) and sülfat<=(sheet["B17"].value) and sülfür<=(sheet["B18"].value) and Pb<=(sheet["B19"].value) and Cd<=(sheet["B20"].value) and Cu<=(sheet["B21"].value) and Zn<=(sheet["B22"].value) and Hg<=(sheet["B23"].value) and Ni<=(sheet["B24"].value):
      print("Girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılabilir:).")
    else:
      print("Malesef girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılamaz.")
if x==17:
    print("Deri, Deri Mamulleri ve Benzeri Sanayileri atıksularının, alıcı ortama deşarj standartlarına uyugunluğuna bakmak için lütfen verilecek olan parametrelere işletmenizin değerlerini net ve doğru bir şekilde giriniz.")
    KOİ=float(input("Kimyasal Oksijen İhtiyacı (KOİ) değerini giriniz="))
    pH=float(input("pH değerini giriniz="))
    renk=float(input("Renk değerini giriniz="))
    yağ=float(input("Yağ ve Gres değerini giriniz="))
    AKM=float(input("Askıda Katı Madde (AKM) değerini giriniz="))
    ZSF=float(input("Balık Biyodeneyi (ZSF) değerini giriniz="))
    toplamkrom=float(input("Toplam Krom değerini giriniz="))
    sülfür=float(input("Sülfür değerini giriniz="))
    import openpyxl
    from openpyxl import Workbook,load_workbook
    import pandas as pd
    book=load_workbook("deri.xlsx")
    sheet=book.active
    df=pd.read_excel("deri.xlsx")
    print(df)
    print("(Girdiğiniz işletmenin, parametrelerinin en fazla alabileceği değerler yukarıdaki tabloda belirtilmiştir.)")
    if KOİ<=(sheet["B2"].value) and 6<=(pH)<=9 and renk<=(sheet["B4"].value) and yağ<=(sheet["B5"].value) and AKM<=(sheet["B6"].value) and ZSF<=(sheet["B7"].value) and toplamkrom<=(sheet["B8"].value) and sülfür<=(sheet["B9"].value):
      print("Girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılabilir:).")
    else:
      print("Malesef girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılamaz.")
if x==18:
    print("Evsel Nitelikli atıksularının, alıcı ortama deşarj standartlarına uyugunluğuna bakmak için lütfen verilecek olan parametrelere işletmenizin değerlerini net ve doğru bir şekilde giriniz.")
    KOİ=float(input("Kimyasal Oksijen İhtiyacı (KOİ) değerini giriniz="))
    pH=float(input("pH değerini giriniz="))
    AKM=float(input("Askıda Katı Madde (AKM) değerini giriniz="))
    BOİ=float(input("Biyokimyasal Oksijen İhtiyacı (BOİ) değerini giriniz="))
    import openpyxl
    from openpyxl import Workbook,load_workbook
    import pandas as pd
    book=load_workbook("evsel.xlsx")
    sheet=book.active
    df=pd.read_excel("evsel.xlsx")
    print(df)
    print("(Girdiğiniz işletmenin, parametrelerinin en fazla alabileceği değerler yukarıdaki tabloda belirtilmiştir.)")
    if KOİ<=(sheet["B2"].value) and 6<=(pH)<=9 and AKM<=(sheet["B4"].value) and BOİ<=(sheet["B5"].value):
      print("Girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılabilir:).")
    else:
      print("Malesef girdiğiniz değerler doğrultusunda alıcı ortama deşarj yapılamaz.")
if x==19:
    print("Atıksuların Atıksu Altyapı Tesislerine deşarjında öngürülen atıksu standartları uyugunluğuna bakmak için lütfen verilecek olan parametrelere işletmenizin değerlerini net ve doğru bir şekilde giriniz.")
    KOİ=float(input("Kimyasal Oksijen İhtiyacı (KOİ) değerini giriniz="))
    pH=float(input("pH değerini giriniz="))
    yağ=float(input("Yağ ve Gres değerini giriniz="))
    AKM=float(input("Askıda Katı Madde (AKM) değerini giriniz="))
    sıcaklık=float(input("Sıcaklık değerini giriniz="))
    BOİ=float(input("Biyokimyasal Oksijen İhtiyacı (BOİ) değerini giriniz="))
    toplamazot=float(input("Toplam Azot değerini giriniz="))
    toplamfosfor=float(input("Toplam Fosfor değerini giriniz="))
    fenol=float(input("Fenol değerini giriniz="))
    sülfat=float(input("Sülfat değerini giriniz="))
    arsenik=float(input("Arsenik değerini giriniz="))
    toplamkurşun=float(input("Toplam Kurşun değerini giriniz="))
    toplamciva=float(input("Toplam Cıva değerini giriniz="))
    toplamkadminyum=float(input("Toplam Kadminyum değerini giriniz="))
    toplamsiyanür=float(input("Toplam Siyanür değerini giriniz="))
    toplamkrom=float(input("Toplam Krom değerini giriniz="))
    serbestklor=float(input("Serbest Klor değerini giriniz="))
    toplamsülfür=float(input("Toplam Sülfür değerini giriniz="))
    toplambakır=float(input("Toplam Bakır değerini giriniz="))
    toplamnikel=float(input("Toplam Nikel değerini giriniz="))
    toplamçinko=float(input("Toplam Çinko değerini giriniz="))
    toplamkalay=float(input("Toplam Kalay değerini giriniz="))
    toplamgümüş=float(input("Toplam Gümüş değerini giriniz="))
    import openpyxl
    from openpyxl import Workbook,load_workbook
    import pandas as pd
    book=load_workbook("atıksu.xlsx")
    sheet=book.active
    df=pd.read_excel("atıksu.xlsx")
    print(df)
    print("(Girdiğiniz işletmenin, parametrelerinin en fazla alabileceği değerler yukarıdaki tabloda belirtilmiştir.)")
    if KOİ<=(sheet["B2"].value) and 6<=(pH)<=10 and yağ<=(sheet["B4"].value) and AKM<=(sheet["B5"].value) and sıcaklık<=(sheet["B6"].value) and BOİ<=(sheet["B7"].value) and toplamazot<=(sheet["B8"].value) and toplamfosfor<=(sheet["B9"].value) and fenol<=(sheet["B10"].value) and sülfat<=(sheet["B11"].value) and arsenik<=(sheet["B12"].value) and toplamkurşun<=(sheet["B13"].value) and toplamciva<=(sheet["B14"].value) and toplamkadminyum<=(sheet["B15"].value) and toplamsiyanür<=(sheet["B16"].value) and toplamkrom<=(sheet["B17"].value) and serbestklor<=(sheet["B18"].value) and toplamsülfür<=(sheet["B19"].value) and toplambakır<=(sheet["B20"].value) and toplamnikel<=(sheet["B21"].value) and toplamçinko<=(sheet["B22"].value) and toplamkalay<=(sheet["B23"].value) and toplamgümüş<=(sheet["B24"].value):
      print("Girdiğiniz değerler doğrultusunda deşarj yapılabilir:).")
    else:
      print("Malesef girdiğiniz değerler doğrultusunda deşarj yapılamaz.")

